[build-system]
requires = ["poetry-core>=1.2.0", "wheel"]
build-backend = "poetry.core.masonry.api"


[tool.coverage.run]
branch = true
relative_files = true
omit = [".tox/*", "tests/*"]


[tool.poetry]
name = "OpenSudoku"
version = "0.1.0"
description = "An open Python implementation of the famous sudoku puzzle."

packages = [{ include = "open_sudoku", from = "src" }]

authors = ["Lari Liuhamo <lari.liuhamo+pypi@gmail.com>"]
maintainers = ["Lari Liuhamo <lari.liuhamo+pypi@gmail.com>"]

include = []
license = "MIT"
readme = "README.md"

homepage = "https://pypi.org/project/OpenSudoku/"
repository = "https://github.com/Diapolo10/OpenSudoku"
documentation = "https://github.com/Diapolo10/OpenSudoku/tree/main/docs"

keywords = ["python3"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
    "Typing :: Typed",
]


[tool.poetry.dependencies]
python = "^3.14.0"


[tool.poetry.group.dev.dependencies]
mypy = "^2.3.1"


[tool.poetry.group.linters]
optional = true


[tool.poetry.group.linters.dependencies]
ruff = "^0.16.7"


[tool.poetry.group.tests]
optional = true


[tool.poetry.group.tests.dependencies]
pytest = "^9.1.1"
pytest-cov = "^7.1.0"
tox = "^4.61.4"
tox-gh-actions = "^3.5.0"


[tool.poetry.urls]
"Tracker" = "https://github.com/Diapolo10/OpenSudoku/issues"
"Changelog" = "https://github.com/Diapolo10/OpenSudoku/blob/main/CHANGELOG.md"

[tool.pytest]
addopts = [
    "--cov=./",
    "--cov-append",
    "--cov-report=html:tests/reports/coverage-html",
    "--cov-report=term-missing:skip-covered",
    "--cov-report=xml:tests/reports/coverage.xml",
    "--doctest-modules",
    "--durations=5",
    "--durations-min=1.0",
    "--ignore=docs/",
]
minversion = "9.0"
testpaths = ["tests"]


[tool.ruff]
lint.select = ["ALL"]
lint.ignore = [
    "COM812",  # Missing trailing comma (disabled due to formatter conflict)
    "CPY001",  # Missing copyright notice at the top of the file
    "D203",    # One blank line before class docstring
    "D212",    # Multi-line summary first line
    "ISC001",  # Single-line implicit string concatenation (disabled due to formatter conflict)
    "PLR0913", # Too many arguments
    "Q000",    # Single quotes found but double quotes preferred
]
line-length = 120
show-fixes = true
src = ["src"]


[tool.ruff.lint.flake8-copyright]
author = "Lari Liuhamo"


[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
multiline-quotes = "double"


[tool.ruff.lint.mccabe]
max-complexity = 10


[tool.ruff.lint.per-file-ignores]
# https://beta.ruff.rs/docs/rules/
"__init__.py" = ["F401", "F403", "F405", "PGH003"]
"tests/*" = ["ANN", "ARG", "INP001", "S101"]


[tool.ruff.lint.pylint]
max-args = 15
max-branches = 20
max-returns = 10
max-statements = 80


[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"


[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py314
skip_missing_interpreters = true

[gh-actions]
python =
    3.14: py314

[testenv]
passenv = GITHUB_*
allowlist_externals = poetry

commands =
    poetry run pytest
    poetry run coverage report
"""
